#!/usr/bin/env python3
"""
Set Shopify Store Home Page
Modifies the theme's index.liquid template to redirect to the custom welcome page
"""

import os
import json
import requests
import sys

# Configuration
SHOPIFY_STORE_DOMAIN = os.environ.get('SHOPIFY_STORE_DOMAIN')
SHOPIFY_ACCESS_TOKEN = os.environ.get('SHOPIFY_SECRET_KEY')
API_VERSION = '2024-10'

if not SHOPIFY_STORE_DOMAIN or not SHOPIFY_ACCESS_TOKEN:
    print("❌ Missing required environment variables:")
    print("   SHOPIFY_STORE_DOMAIN")
    print("   SHOPIFY_SECRET_KEY")
    sys.exit(1)

def shopify_request(method, endpoint, data=None):
    """Make a request to the Shopify Admin API"""
    url = f"https://{SHOPIFY_STORE_DOMAIN}/admin/api/{API_VERSION}{endpoint}"
    headers = {
        'X-Shopify-Access-Token': SHOPIFY_ACCESS_TOKEN,
        'Content-Type': 'application/json'
    }

    try:
        if method == 'GET':
            response = requests.get(url, headers=headers, timeout=30)
        elif method == 'PUT':
            response = requests.put(url, headers=headers, json=data, timeout=30)
        elif method == 'POST':
            response = requests.post(url, headers=headers, json=data, timeout=30)
        else:
            raise ValueError(f"Unsupported method: {method}")

        response.raise_for_status()
        return response.json()

    except requests.exceptions.RequestException as e:
        print(f"❌ API request failed: {e}")
        if hasattr(e, 'response') and e.response is not None:
            print(f"Response status: {e.response.status_code}")
            print(f"Response body: {e.response.text}")
        raise

def get_active_theme():
    """Get the currently active theme"""
    print("🎨 Fetching active theme...")
    data = shopify_request('GET', '/themes.json')

    for theme in data['themes']:
        if theme['role'] == 'main':
            print(f"✅ Found active theme: {theme['name']} (ID: {theme['id']})")
            return theme

    raise Exception("No active theme found")

def get_theme_asset(theme_id, asset_key):
    """Get a specific theme asset"""
    print(f"📄 Fetching asset: {asset_key}...")
    endpoint = f"/themes/{theme_id}/assets.json?asset[key]={asset_key}"
    data = shopify_request('GET', endpoint)
    return data['asset']

def update_theme_asset(theme_id, asset_key, value):
    """Update a theme asset"""
    print(f"✏️  Updating asset: {asset_key}...")
    endpoint = f"/themes/{theme_id}/assets.json"
    data = {
        'asset': {
            'key': asset_key,
            'value': value
        }
    }
    shopify_request('PUT', endpoint, data)
    print(f"✅ Updated: {asset_key}")

def main():
    print("\n" + "=" * 80)
    print("🏠 Shopify Home Page Setup")
    print("=" * 80 + "\n")

    try:
        # Step 1: Get active theme
        theme = get_active_theme()
        print()

        # Step 2: Get current index.liquid
        print("📋 Step 2: Fetching current home page template...")
        try:
            index_asset = get_theme_asset(theme['id'], 'templates/index.liquid')
            current_size = len(index_asset.get('value', ''))
            print(f"✅ Current template size: {current_size} characters")
        except Exception as e:
            print(f"⚠️  Could not fetch current template: {e}")
            print("   Continuing anyway...")
        print()

        # Step 3: Create new index.liquid that redirects to welcome page
        print("✨ Step 3: Creating new home page template...")
        new_index_template = """{%- comment -%}
  Custom Home Page - Redirects to Welcome Page
  Auto-generated by All Dogs Rock API
  Created: 2025
{%- endcomment -%}

<script>
  // Redirect to the custom welcome page
  window.location.href = '/pages/welcome';
</script>

{%- comment -%}
  Fallback for browsers with JavaScript disabled
{%- endcomment -%}
<noscript>
  <meta http-equiv="refresh" content="0; url=/pages/welcome">
</noscript>

<div style="text-align: center; padding: 50px; font-family: Arial, sans-serif;">
  <h1>Welcome to All Dogs Rock</h1>
  <p>Redirecting to our gallery...</p>
  <p>If you are not redirected automatically, <a href="/pages/welcome">click here</a>.</p>
</div>
"""

        update_theme_asset(theme['id'], 'templates/index.liquid', new_index_template)
        print()

        # Success!
        print("=" * 80)
        print("✅ HOME PAGE SET SUCCESSFULLY!")
        print("=" * 80)
        print()
        print("Your store home page now redirects to:")
        print("   🔗 https://alldogsrockshop.com/pages/welcome")
        print()
        print("Visit your store to see it in action:")
        print("   🌐 https://alldogsrockshop.com")
        print()
        print("=" * 80 + "\n")

        return 0

    except Exception as e:
        print("\n" + "=" * 80)
        print(f"❌ ERROR: {e}")
        print("=" * 80 + "\n")
        return 1

if __name__ == '__main__':
    sys.exit(main())
