#!/bin/bash
# Set Shopify Store Home Page
# This script updates the theme's index.liquid to redirect to /pages/welcome

set -e

# Load environment variables
if [ -f .env.local ]; then
    export $(cat .env.local | grep -v '^#' | grep -v '^$' | xargs)
fi

SHOPIFY_DOMAIN="${SHOPIFY_STORE_DOMAIN}"
ACCESS_TOKEN="${SHOPIFY_SECRET_KEY}"

if [ -z "$SHOPIFY_DOMAIN" ] || [ -z "$ACCESS_TOKEN" ]; then
    echo "❌ Missing required environment variables:"
    echo "   SHOPIFY_STORE_DOMAIN"
    echo "   SHOPIFY_SECRET_KEY"
    exit 1
fi

API_VERSION="2024-10"

echo "================================================================================"
echo "🏠 Shopify Home Page Setup"
echo "================================================================================"
echo ""

# Step 1: Get active theme
echo "🎨 Step 1: Getting active theme..."
THEMES_RESPONSE=$(curl -s -X GET \
  "https://${SHOPIFY_DOMAIN}/admin/api/${API_VERSION}/themes.json" \
  -H "X-Shopify-Access-Token: ${ACCESS_TOKEN}" \
  -H "Content-Type: application/json")

# Extract theme ID (looking for role: "main")
THEME_ID=$(echo "$THEMES_RESPONSE" | grep -o '"id":[0-9]*' | head -1 | grep -o '[0-9]*')
THEME_NAME=$(echo "$THEMES_RESPONSE" | grep -o '"name":"[^"]*"' | head -1 | cut -d'"' -f4)

if [ -z "$THEME_ID" ]; then
    echo "❌ Failed to get active theme"
    echo "Response: $THEMES_RESPONSE"
    exit 1
fi

echo "✅ Found theme: $THEME_NAME (ID: $THEME_ID)"
echo ""

# Step 2: Create new index.liquid template
echo "✨ Step 2: Creating home page redirect template..."

NEW_INDEX_TEMPLATE='{%- comment -%}
  Custom Home Page - Redirects to Welcome Page
  Auto-generated by All Dogs Rock API
{%- endcomment -%}

<script>
  // Redirect to the custom welcome page
  window.location.href = "/pages/welcome";
</script>

{%- comment -%}
  Fallback for browsers with JavaScript disabled
{%- endcomment -%}
<noscript>
  <meta http-equiv="refresh" content="0; url=/pages/welcome">
</noscript>

<div style="text-align: center; padding: 50px; font-family: Arial, sans-serif;">
  <h1>Welcome to All Dogs Rock</h1>
  <p>Redirecting to our gallery...</p>
  <p>If you are not redirected automatically, <a href="/pages/welcome">click here</a>.</p>
</div>'

# Step 3: Update the template
echo "📝 Step 3: Updating theme template..."

# Escape the template for JSON
ESCAPED_TEMPLATE=$(echo "$NEW_INDEX_TEMPLATE" | jq -Rs .)

# Create JSON payload
JSON_PAYLOAD=$(cat <<EOF
{
  "asset": {
    "key": "templates/index.liquid",
    "value": $ESCAPED_TEMPLATE
  }
}
EOF
)

UPDATE_RESPONSE=$(curl -s -w "\n%{http_code}" -X PUT \
  "https://${SHOPIFY_DOMAIN}/admin/api/${API_VERSION}/themes/${THEME_ID}/assets.json" \
  -H "X-Shopify-Access-Token: ${ACCESS_TOKEN}" \
  -H "Content-Type: application/json" \
  -d "$JSON_PAYLOAD")

HTTP_CODE=$(echo "$UPDATE_RESPONSE" | tail -n1)
RESPONSE_BODY=$(echo "$UPDATE_RESPONSE" | head -n-1)

if [ "$HTTP_CODE" = "200" ]; then
    echo "✅ Home page template updated successfully!"
    echo ""
    echo "================================================================================"
    echo "✅ HOME PAGE SET SUCCESSFULLY!"
    echo "================================================================================"
    echo ""
    echo "Your store home page now redirects to:"
    echo "   🔗 https://alldogsrockshop.com/pages/welcome"
    echo ""
    echo "Visit your store to see it in action:"
    echo "   🌐 https://alldogsrockshop.com"
    echo ""
    echo "================================================================================"
    exit 0
else
    echo "❌ Failed to update template (HTTP $HTTP_CODE)"
    echo "Response: $RESPONSE_BODY"
    exit 1
fi
